FROM php:8.2-apache

RUN docker-php-ext-install pdo pdo_mysql

COPY config/apache-prod.conf /etc/apache2/sites-available/000-default.conf
COPY config/php-production.ini /usr/local/etc/php/conf.d/production.ini
COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www/html/img

EXPOSE 80
